appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: qM2BESnR04zMZOHmsQThOlpxDBEZj2ecQ0Ih7GTjXonuwasASHrBwGBXoOg/JFUdBukazCUWLA3RWeYscEyOQRAx+mCSK+QJzdlEkNbdxrCISUjIxmOoH2vt3ifJfcYnr38XoJ1J5MMM32FE61E3NyH+73HtTXV+TGF+dfB1iZX5sETGoZfNj66999f2PDnvElhAy4SSlK9ATHbfWlT1bMRPJoTPLwu/04dJMEJOQXRQYMmuDDTunu7TGVtXVcdY9UO1s3To3sKPxeAq35cXxcMVJ/nnXZTMiei3Jf4jcxg/LQWCwGYa595nsi6/NtY2xCuT5ccgsoVrmsMSK3INBI/pGD4ujem5Qk6CkMZhUoBH8NV3a0f+I92ErtK+jCFEe6o7IrujXRiHAAKocHGP2JW1hzNIGmbnGsmEBFs5K0EBNbVBfEs5k/snobvir1CnRUoaHA8+8vIiNPdil/7LBH4T//Rwf842x/LVcgGfvdqsj4zVNSAeopmgVkYqp35sz1qCqx0jhIreAMqywVCtXf4TCWG4iGysKGQHOW5aPhLiiacI43pteGeL1zYzEEDdJWC8ybvL+FSv+wHnzqt2O7Xk0QpZ6psH4jmcEs27EhobSSukRmkg5JsERnDzNapkxl+h3UK3GF3jP4wzn5EdTq1qkEj5O6U6RFpZsRaN9sc=}
conda_forge_output_validation: true
